name: Build Kernel
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: EAZYBLACK/kernel_build_action@main
      with:
          kernel-url: https://github.com/EmanuelCN/android_kernel_lge_sdm845
          branch: pelt-temp
          config: lineageos_judyln_defconfig
          arch: arm64
          other-clang-url: https://github.com/kdrag0n/proton-clang
          aosp-gcc: true
          submodule: true
          other-clang-branch: master
          anykernel3: true
